inherit_from: .rubocop_todo.yml

---
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - ".github/**/*"
    - "bin/**/*"
  NewCops: enable

Style/FormatStringToken:
  Description: "Use a consistent style for format string tokens."
  Enabled: true
  EnforcedStyle: unannotated

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Strip:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Style/MethodCallWithArgsParentheses:
  IgnoredMethods: [gem, require, include, puts, render, redirect_to, yield,
                   head, respond_with, ruby, source, send_data, instance_eval,
                   require_relative, to, not_to]

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Lint/LiteralInInterpolation:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Lint/SuppressedException:
  AllowComments: true

Lint/ReturnInVoidContext:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
  Enabled: true

Naming/MethodName:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
