---
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - ".github/**/*"
    - "bin/**/*"
  NewCops: enable

Style/FormatStringToken:
  Description: "Use a consistent style for format string tokens."
  Enabled: true
  EnforcedStyle: unannotated

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Style/MethodCallWithArgsParentheses:
  IgnoredMethods: [gem, require, include, puts, render, redirect_to, yield,
                   head, respond_with, ruby, source, send_data, instance_eval,
                   require_relative, to, not_to]

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Lint/SuppressedException:
  AllowComments: true

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/xumlidot/diagram/xmi/klass.rb'

Lint/EmptyClass: # (new in 1.3)
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'