---
name: Rspec Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rspec:
    name: RSpec tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rspec spec
